
import { 
  QrCode, AlignLeft, Image as ImageIcon, Binary, 
  Network, Activity, Timer, RefreshCw, FileDiff, Wallet,
  Grid2X2, StickyNote, KeyRound, Scale, Clock, Palette, 
  FileJson, FileType, Calculator, Trophy, Stamp, Dices, BoxSelect, 
  Fingerprint, Type, Disc, ArrowRightLeft, ImageOff, Hash, Search, 
  BookOpen, ListTodo, FileStack, Code, Database, CalendarDays, Globe, 
  Pipette, Bath
} from 'lucide-react';
import { Tool } from '../types';

export const TOOLS: Tool[] = [
  { id: 'qrcode', name: 'QRコード生成', path: '/qrcode', description: 'URLを入力してQRコードを作成', icon: QrCode, color: 'text-blue-500', lightBg: 'bg-blue-50', longDescription: '安全で高速なオンラインQRコード作成ツール。商用利用無料で、生成データはサーバーに保存されません。', keywords: ['QRコード作成', '無料', '高画質'] },
  { id: 'count', name: '文字数カウンター', path: '/count', description: 'リアルタイムで文字数・行数をカウント', icon: AlignLeft, color: 'text-green-500', lightBg: 'bg-green-50', longDescription: 'レポートやSNS投稿に便利な高機能文字数カウント。ひらがな・漢字の比率分析も。', keywords: ['文字数カウント', '原稿用紙換算'] },
  { id: 'bath-prevent', name: '風呂キャン防止', path: '/bath', description: '5秒で強制的に風呂へ向かわせる', icon: Bath, color: 'text-cyan-500', lightBg: 'bg-cyan-50', longDescription: '「お風呂に入るのが面倒」という心理的障壁を、5秒の強制カウントダウンと鼓動演出で突破します。', keywords: ['風呂キャン', 'モチベーション', 'タイマー'] },
  { id: 'picker', name: 'カラーピッカー', path: '/picker', description: 'RGB/HSL/CMYK変換・画像から抽出', icon: Pipette, color: 'text-pink-600', lightBg: 'bg-pink-50', longDescription: 'Web制作に最適なカラーピッカー。スポイト機能で画像から色を抽出できます。', keywords: ['カラーピッカー', 'HEX変換', 'スポイト'] },
  { id: 'password', name: 'パスワード生成', path: '/password', description: '強力なランダムパスワードを生成', icon: KeyRound, color: 'text-emerald-600', lightBg: 'bg-emerald-50', longDescription: '強力で安全なパスワードをブラウザで生成。記号の有無や履歴保存にも対応。', keywords: ['パスワード生成', 'セキュリティ', 'ランダム'] },
  { id: 'kakeibo', name: 'まいつーる家計簿', path: '/kakeibo', description: '登録不要の多機能家計簿', icon: Wallet, color: 'text-yellow-600', lightBg: 'bg-yellow-50', longDescription: 'ブラウザ保存で安心の無料家計簿。円グラフ分析、サブスク管理、目標設定機能。', keywords: ['家計簿', '節約', '無料ツール'] },
  { id: 'pdf', name: 'PDFツール', path: '/pdf', description: '結合・解除・ページ回転', icon: FileStack, color: 'text-red-600', lightBg: 'bg-red-50', longDescription: 'ブラウザ完結型のPDF編集。結合、パスワード解除、回転、白塗りが安全に行えます。', keywords: ['PDF結合', 'PDF編集', 'PDF解除'] },
  { id: 'resize', name: '画像リサイズ', path: '/resize', description: 'アスペクト比維持でサイズ変更', icon: ImageIcon, color: 'text-purple-500', lightBg: 'bg-purple-50', longDescription: '比率を保ったまま画像のピクセルサイズを変更。ブログやSNS投稿の軽量化に。', keywords: ['画像リサイズ', 'サイズ変更', '画像軽量化'] },
  { id: 'convert', name: 'Base64変換', path: '/convert', description: 'ファイルとBase64の相互変換', icon: FileType, color: 'text-orange-500', lightBg: 'bg-orange-50', longDescription: '画像やファイルをBase64テキストに変換。開発時のデータURI作成に便利です。', keywords: ['Base64変換', 'エンコード', 'デコード'] },
  { id: 'ip', name: 'IP確認・ポート', path: '/ip', description: '自分のIP確認とポート開放テスト', icon: Network, color: 'text-sky-500', lightBg: 'bg-sky-50', longDescription: 'グローバルIPアドレスの即時確認と、特定ポートの外部開放チェック。', keywords: ['IP確認', 'ポート開放', 'ネットワーク'] },
  { id: 'speed', name: 'スピードテスト', path: '/speed', description: '回線速度の計測', icon: Activity, color: 'text-rose-500', lightBg: 'bg-rose-50', longDescription: 'インターネット回線のダウンロード・アップロード速度をリアルタイム計測。', keywords: ['スピードテスト', '回線速度', 'ネット診断'] },
  { id: 'server-loc', name: 'サーバー位置情報', path: '/server-loc', description: 'ドメインから位置を特定', icon: Globe, color: 'text-indigo-500', lightBg: 'bg-indigo-50', longDescription: 'IPやドメインからサーバーの物理的な所在地をマップ表示。トレースルート対応。', keywords: ['サーバー場所', 'ドメイン検索', 'IP住所'] },
  { id: 'binary', name: '2進数変換', path: '/binary', description: '10進数と2進数の相互変換', icon: Binary, color: 'text-teal-500', lightBg: 'bg-teal-50', longDescription: 'プログラミングに便利な10進数・2進数・16進数の相互変換ツール。', keywords: ['2進数変換', 'バイナリ', 'プログラミング'] },
  { id: 'timer', name: 'タイマー', path: '/timer', description: 'タイマー・SW・ポモドーロ', icon: Timer, color: 'text-rose-600', lightBg: 'bg-rose-600/10', longDescription: '多機能タイマー。集中力を高めるポモドーロやストップウォッチ機能を搭載。', keywords: ['タイマー', 'ポモドーロ', '集中'] },
  { id: 'notepad', name: 'メモ帳', path: '/notepad', description: 'リッチテキスト対応のメモ', icon: StickyNote, color: 'text-lime-600', lightBg: 'bg-lime-50', longDescription: 'ブラウザ保存の多機能メモ帳。コードハイライトやリッチテキスト編集に対応。', keywords: ['オンラインメモ', 'メモ帳', 'テキスト編集'] },
  { id: 'calculator', name: '計算機', path: '/calculator', description: '履歴付きシンプル計算機', icon: Calculator, color: 'text-orange-600', lightBg: 'bg-orange-50', longDescription: '計算履歴が残るシンプルなWeb電卓。直感的な操作が可能です。', keywords: ['電卓', '計算機', 'オンライン電卓'] },
  { id: 'scoreboard', name: 'スコアボード', path: '/scoreboard', description: 'タイマー付き得点板', icon: Trophy, color: 'text-blue-700', lightBg: 'bg-blue-50', longDescription: 'スポーツやゲームで使える多機能スコアボード. タイマー機能付き。', keywords: ['得点板', 'スコアボード', 'スポーツ'] },
  { id: 'unit', name: '単位変換', path: '/unit', description: '長さ・重さ・温度・面積', icon: Scale, color: 'text-fuchsia-500', lightBg: 'bg-fuchsia-50', longDescription: '長さ、重さ、温度、面積など、日常で使う様々な単位を相互変換します。', keywords: ['単位変換', '単位計算', '換算'] },
  { id: 'random', name: 'ランダム生成', path: '/random', description: '数字のランダム生成', icon: Dices, color: 'text-rose-500', lightBg: 'bg-rose-50', longDescription: '指定した範囲内で乱数を生成。重複の可否も設定可能です。', keywords: ['乱数生成', 'ランダム', '数字'] },
  { id: 'ratio', name: 'アスペクト比計算', path: '/ratio', description: '比率と解像度の計算', icon: BoxSelect, color: 'text-cyan-500', lightBg: 'bg-cyan-50', longDescription: '縦横のサイズからアスペクト比を算出。FHDや4Kなどのプリセットも充実. ', keywords: ['アスペクト比', '解像度', '比率計算'] },
  { id: 'uuid', name: 'UUID生成', path: '/uuid', description: 'v4 UUIDを一括生成', icon: Fingerprint, color: 'text-violet-500', lightBg: 'bg-violet-50', longDescription: '開発で必要なUUID(v4)を瞬時に、かつ一括で生成します。', keywords: ['UUID生成', '開発ツール', 'GUID'] },
  { id: 'case', name: 'ケース変換', path: '/case', description: 'キャメル・スネーク等', icon: Type, color: 'text-orange-500', lightBg: 'bg-orange-50', longDescription: 'テキストのケース（キャメルケース、スネークケース、ケバブケース等）を一括変換。', keywords: ['ケース変換', '命名規則', '開発'] },
  { id: 'roulette', name: 'ルーレット', path: '/roulette', description: '項目自由なルーレット', icon: Disc, color: 'text-pink-500', lightBg: 'bg-pink-50', longDescription: 'ランチの選択やゲームの抽選に。項目を自由にカスタマイズできるルーレット。', keywords: ['ルーレット', '抽選', 'おみくじ'] },
  { id: 'text-conv', name: '全角半角変換', path: '/text-conv', description: 'テキストの形式一括変換', icon: ArrowRightLeft, color: 'text-indigo-600', lightBg: 'bg-indigo-50', longDescription: '英数字やカタカナの全角・半角をボタン一つで一括変換。', keywords: ['全角半角', '文字変換', '整形'] },
  { id: 'image-conv', name: '画像形式変換', path: '/image-conv', description: 'PNG/JPG/WEBP/ICO変換', icon: RefreshCw, color: 'text-pink-500', lightBg: 'bg-pink-50', longDescription: '画像のファイル形式をブラウザ上で高速変換。ICO（ファビコン用）にも対応。', keywords: ['画像変換', 'PNG変換', 'WEBP変換'] },
  { id: 'hash', name: 'ハッシュ生成', path: '/hash', description: 'SHA-256等の生成', icon: Hash, color: 'text-slate-600', lightBg: 'bg-slate-100', longDescription: 'テキストからSHA-256やSHA-512などのセキュアなハッシュ値を生成。', keywords: ['ハッシュ生成', 'SHA256', '暗号化'] },
  { id: 'regex', name: '正規表現', path: '/regex', description: 'マッチングテスト', icon: Search, color: 'text-teal-600', lightBg: 'bg-teal-50', longDescription: '正規表現のパターンマッチングをリアルタイムでテスト・検証。', keywords: ['正規表現', 'Regex', 'テスト'] },
  { id: 'flashcards', name: '暗記カード', path: '/flashcards', description: '自作単語帳で学習', icon: BookOpen, color: 'text-blue-500', lightBg: 'bg-blue-50', longDescription: 'ブラウザで使える自作の暗記カード。試験対策や言語学習に最適。', keywords: ['暗記', '単語帳', '学習'] },
  { id: 'tasks', name: 'タスク管理', path: '/tasks', description: '優先度付きTODOリスト', icon: ListTodo, color: 'text-teal-500', lightBg: 'bg-teal-50', longDescription: 'シンプルで使いやすいタスク管理。ブラウザ保存なのでログイン不要. ', keywords: ['TODOリスト', 'タスク管理', '効率化'] },
  { id: 'html', name: 'HTMLエディタ', path: '/html', description: 'ライブプレビュー付き', icon: Code, color: 'text-orange-600', lightBg: 'bg-orange-50', longDescription: 'HTML/CSSを記述して即座にプレビュー。XSS保護付きで安全。', keywords: ['HTMLエディタ', 'プレビュー', 'コーディング'] },
  { id: 'sql', name: 'オンラインSQL', path: '/sql', description: 'ブラウザでSQL練習', icon: Database, color: 'text-blue-500', lightBg: 'bg-blue-50', longDescription: 'データベース不要でSQLのクエリをブラウザ上で実行・練習。', keywords: ['SQL練習', 'データベース', 'SQL実行'] },
  { id: 'date', name: '日付計算', path: '/date', description: '期間と日数の計算', icon: CalendarDays, color: 'text-indigo-500', lightBg: 'bg-indigo-50', longDescription: '2つの日付間の日数計算や、特定の日から○日後の日付を計算。', keywords: ['日付計算', '日数差', 'カレンダー'] },
  { id: 'subnet', name: 'IPサブネット', path: '/subnet', description: 'サブネット分割計算', icon: Network, color: 'text-cyan-600', lightBg: 'bg-cyan-50', longDescription: 'IPアドレスとマスクからサブネット範囲を算出。エンジニア必携。', keywords: ['サブネット計算', 'IP範囲', 'ネットワーク'] },
  { id: 'palette', name: 'カラーパレット', path: '/palette', description: '配色パレット生成', icon: Palette, color: 'text-indigo-500', lightBg: 'bg-indigo-50', longDescription: 'デザインで使える美しい配色パレットをランダムに生成。', keywords: ['配色パレット', 'デザイン', '色'] },
  { id: 'json', name: 'JSON整形', path: '/json', description: 'JSONの整形と検証', icon: FileJson, color: 'text-yellow-500', lightBg: 'bg-yellow-50', longDescription: '読みづらいJSONファイルをきれいに整形・検証。圧縮も可能。', keywords: ['JSON整形', 'デバッグ', 'フォーマッタ'] },
  { id: 'markdown', name: 'Markdown', path: '/markdown', description: 'エディタとプレビュー', icon: FileType, color: 'text-slate-700', lightBg: 'bg-slate-100', longDescription: 'Markdown記法をブラウザ上でリアルタイムにHTML変換・表示。', keywords: ['Markdown', 'エディタ', 'プレビュー'] },
  { id: 'watermarker', name: '画像透かし', path: '/watermarker', description: 'ロゴや文字を合成', icon: Stamp, color: 'text-sky-500', lightBg: 'bg-sky-50', longDescription: '画像に著作権保護のための透かし（文字や画像）を合成します。', keywords: ['透かし合成', '著作権', '画像加工'] },
  { id: 'exif', name: 'Exif削除', path: '/exif', description: '画像の位置情報を除去', icon: ImageOff, color: 'text-red-500', lightBg: 'bg-red-50', longDescription: '写真に含まれるGPS情報や個人情報を削除してプライバシーを保護。', keywords: ['Exif削除', 'プライバシー', 'GPS消去'] },
  { id: 'diff', name: 'テキストDiff', path: '/diff', description: '文章の差分を比較', icon: FileDiff, color: 'text-cyan-700', lightBg: 'bg-cyan-50', longDescription: '2つの文章を比較して、追加・変更箇所を分かりやすく表示。', keywords: ['テキスト比較', 'Diff', '差分'] },
  { id: 'timestamp', name: 'Unix時間変換', path: '/timestamp', description: 'タイムスタンプ相互変換', icon: Clock, color: 'text-slate-500', lightBg: 'bg-slate-100', longDescription: 'Unixタイムスタンプと日時形式を瞬時に相互変換。', keywords: ['Unix時間', 'タイムスタンプ', '日付変換'] }
];
