
import { 
  QrCode, AlignLeft, Image as ImageIcon, Binary, 
  Network, Activity, Timer, RefreshCw, FileDiff, Wallet,
  StickyNote, KeyRound, Scale, Clock, Palette, 
  FileJson, FileType, Calculator, Trophy, Stamp, Dices, BoxSelect, 
  Fingerprint, Type, Disc, ArrowRightLeft, ImageOff, Hash, Search, 
  BookOpen, ListTodo, FileStack, Code, Database, CalendarDays, Globe, 
  Pipette, Bath, Share2, Layers, Monitor
} from 'lucide-react';
import { Tool } from '../types';

export const TOOLS: Tool[] = [
  { id: 'qrcode', name: 'QRコード生成', path: '/qrcode', description: 'URLを入力してQRコードを作成', icon: QrCode, color: 'text-blue-500', lightBg: 'bg-blue-50' },
  { id: 'bundle', name: 'URLまとめURL', path: '/bundle', description: '複数URLを1つのリンクに集約', icon: Layers, color: 'text-cyan-500', lightBg: 'bg-cyan-50' },
  { id: 'share', name: 'テキスト共有', path: '/share', description: '期限付きURLでテキストを共有', icon: Share2, color: 'text-emerald-500', lightBg: 'bg-emerald-50' },
  { id: 'freebord', name: 'マイボード', path: '/freebord/', description: '専用ページ', icon: Monitor, color: 'text-indigo-500', lightBg: 'bg-indigo-50', isExternal: true },
  { id: 'count', name: '文字数カウンター', path: '/count', description: 'リアルタイムで文字数・行数をカウント', icon: AlignLeft, color: 'text-green-500', lightBg: 'bg-green-50' },
  { id: 'bath', name: '風呂キャン防止ツール', path: '/bath', description: '5秒で強制的に風呂へ向かわせる', icon: Bath, color: 'text-cyan-500', lightBg: 'bg-cyan-50' },
  { id: 'picker', name: 'カラーピッカー', path: '/picker', description: 'RGB/HSL/CMYK変換・画像から抽出', icon: Pipette, color: 'text-pink-600', lightBg: 'bg-pink-50' },
  { id: 'password', name: 'パスワード生成', path: '/password', description: '強力なランダムパスワードを生成', icon: KeyRound, color: 'text-emerald-600', lightBg: 'bg-emerald-50' },
  { id: 'kakeibo', name: 'まいつーる家計簿', path: '/kakeibo', description: '登録不要の多機能家計簿', icon: Wallet, color: 'text-yellow-600', lightBg: 'bg-yellow-50' },
  { id: 'pdf', name: 'PDFツール', path: '/pdf', description: '結合・解除・ページ回転', icon: FileStack, color: 'text-red-600', lightBg: 'bg-red-50' },
  { id: 'resize', name: '画像リサイズ', path: '/resize', description: 'アスペクト比維持でサイズ変更', icon: ImageIcon, color: 'text-purple-500', lightBg: 'bg-purple-50' },
  { id: 'convert', name: 'Base64変換', path: '/convert', description: 'ファイルとBase64の相互変換', icon: FileType, color: 'text-orange-500', lightBg: 'bg-orange-50' },
  { id: 'ip', name: 'IP確認・ポート', path: '/ip', description: '自分のIP確認とポート開放テスト', icon: Network, color: 'text-sky-500', lightBg: 'bg-sky-50' },
  { id: 'speed', name: 'スピードテスト', path: '/speed', description: '回線速度の計測', icon: Activity, color: 'text-rose-500', lightBg: 'bg-rose-50' },
  { id: 'server-loc', name: 'サーバー位置情報', path: '/server-loc', description: 'ドメインやIPの所在地を表示', icon: Globe, color: 'text-indigo-500', lightBg: 'bg-indigo-50' },
  { id: 'binary', name: '2進数変換', path: '/binary', description: '10進数と2進数の相互変換', icon: Binary, color: 'text-teal-500', lightBg: 'bg-teal-50' },
  { id: 'timer', name: 'タイマー・SW', path: '/timer', description: '多機能タイマーとストップウォッチ', icon: Timer, color: 'text-rose-600', lightBg: 'bg-rose-50' },
  { id: 'notepad', name: 'Webメモ帳（プレビュー）', path: '/notepad', description: 'ブラウザ保存の多機能テキストエディタ', icon: StickyNote, color: 'text-lime-600', lightBg: 'bg-lime-50' },
  { id: 'calculator', name: 'オンライン計算機', path: '/calculator', description: '履歴機能付きのシンプル計算機', icon: Calculator, color: 'text-orange-600', lightBg: 'bg-orange-50' },
  { id: 'scoreboard', name: 'スコアボード', path: '/scoreboard', description: '試合やゲームの得点管理', icon: Trophy, color: 'text-yellow-700', lightBg: 'bg-yellow-50' },
  { id: 'unit', name: '単位変換', path: '/unit', description: '長さ・重さ・温度などの変換', icon: Scale, color: 'text-fuchsia-500', lightBg: 'bg-fuchsia-50' },
  { id: 'random', name: 'ランダム生成', path: '/random', description: '乱数や抽選用リストの作成', icon: Dices, color: 'text-rose-500', lightBg: 'bg-rose-50' },
  { id: 'ratio', name: 'アスペクト比計算', path: '/ratio', description: '画像や動画の縦横比を算出', icon: BoxSelect, color: 'text-cyan-500', lightBg: 'bg-cyan-50' },
  { id: 'uuid', name: 'UUID生成', path: '/uuid', description: 'ランダムなUUID(v4)を生成', icon: Fingerprint, color: 'text-violet-500', lightBg: 'bg-violet-50' },
  { id: 'case', name: 'ケース変換', path: '/case', description: 'キャメル/スネークケース等の変換', icon: Type, color: 'text-orange-500', lightBg: 'bg-orange-50' },
  { id: 'roulette', name: 'ルーレット', path: '/roulette', description: '項目を入力して抽選', icon: Disc, color: 'text-pink-500', lightBg: 'bg-pink-50' },
  { id: 'text-conv', name: '全角半角変換', path: '/text-conv', description: '英数字・カタカナの一括変換', icon: ArrowRightLeft, color: 'text-indigo-500', lightBg: 'bg-indigo-50' },
  { id: 'image-conv', name: '画像形式変換', path: '/image-conv', description: 'PNG/JPG/WEBP等の相互変換', icon: RefreshCw, color: 'text-pink-500', lightBg: 'bg-pink-50' },
  { id: 'hash', name: 'ハッシュ生成', path: '/hash', description: 'SHA-256などのハッシュ値計算', icon: Hash, color: 'text-slate-600', lightBg: 'bg-slate-50' },
  { id: 'regex', name: '正規表現チェッカー', path: '/regex', description: 'RegExpパターンの動作検証', icon: Search, color: 'text-teal-500', lightBg: 'bg-teal-50' },
  { id: 'flashcards', name: '暗記カード', path: '/flashcards', description: '自分専用の単語帳を作成', icon: BookOpen, color: 'text-blue-500', lightBg: 'bg-blue-50' },
  { id: 'tasks', name: 'タスク管理', path: '/tasks', description: 'シンプルなTODOリスト', icon: ListTodo, color: 'text-teal-500', lightBg: 'bg-teal-50' },
  { id: 'html', name: 'HTMLエディタ', path: '/html', description: 'プレビュー付きのコード練習', icon: Code, color: 'text-orange-600', lightBg: 'bg-orange-50' },
  { id: 'sql', name: 'オンラインSQL', path: '/sql', description: 'ブラウザでSQLクエリを試行', icon: Database, color: 'text-blue-500', lightBg: 'bg-blue-50' },
  { id: 'date', name: '日付・期間計算', path: '/date', description: '日数差や指定日後の算出', icon: CalendarDays, color: 'text-indigo-500', lightBg: 'bg-indigo-50' },
  { id: 'subnet', name: 'IPサブネット計算', path: '/subnet', description: 'CIDR計算と包含判定', icon: Network, color: 'text-cyan-500', lightBg: 'bg-cyan-50' },
  { id: 'palette', name: 'カラーパレット', path: '/palette', description: 'デザイン用の配色生成', icon: Palette, color: 'text-indigo-500', lightBg: 'bg-indigo-50' },
  { id: 'json', name: 'JSON整形', path: '/json', description: '読みやすくフォーマット・検証', icon: FileJson, color: 'text-yellow-500', lightBg: 'bg-yellow-50' },
  { id: 'markdown', name: 'Markdownエディタ', path: '/markdown', description: 'マークダウンのリアルタイム変換', icon: FileType, color: 'text-slate-700', lightBg: 'bg-slate-50' },
  { id: 'watermarker', name: '画像透かし合成', path: '/watermarker', description: 'ロゴや文字を写真に合成', icon: Stamp, color: 'text-sky-500', lightBg: 'bg-sky-50' },
  { id: 'exif', name: 'Exif削除', path: '/exif', description: '写真の個人情報を一括除去', icon: ImageOff, color: 'text-red-500', lightBg: 'bg-red-50' },
  { id: 'diff', name: 'テキストDiff', path: '/diff', description: '2つの文章の差分を比較', icon: FileDiff, color: 'text-cyan-600', lightBg: 'bg-cyan-50' },
  { id: 'timestamp', name: 'Unix時間変換', path: '/timestamp', description: 'UNIX時間と日時の相互変換', icon: Clock, color: 'text-slate-600', lightBg: 'bg-slate-50' },
];
